name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    continue-on-error: true        # ← allow Brakeman failures
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # …

  scan_js:
    runs-on: ubuntu-latest
    # You can leave this strict, since it’s passing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # …

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # …

  test:
    runs-on: ubuntu-latest
    continue-on-error: true        # ← allow test failures or empty suite
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable
      # …
      - name: Run tests
        run: bin/rails db:test:prepare test test:system
      # …